spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cblog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 1234
    username: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 20000
      connection-timeout: 20000
      max-lifetime: 18000
      maximum-pool-size: 500
    jpa:
      show-sql: true
      generate-ddl: true
      database: mysql
#        open-in-view: true
      hibernate:
        ddl-auto: update
  thymeleaf:
    cache: false

  level:
    root: error
    com.cqw: error
  file:
    path: D:/log/
server:
  port: 8080

