spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    password: 1234
    username: root

  profiles:
    active: dev
  devtools:
    restart:
      log-condition-evaluation-delta: false
  messages:
    basename: i18n/messages
logging:
  level:
    root: error
    com.cqw: error
  file:
    path: D:\cblog\cblog.log
comment.avatar: /static/images/avatar
